name: get_in_ppx pipeline

on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Check the issue
      - working-directory: .github/actions
        run: npm i
      - working-directory: .github/actions
        id: check
        run: node check.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup
        run: npm i -g esy@latest

      - uses: actions/cache@v1
        with:
          path: ~/.esy
          key: ${{ runner.os }}-node-${{ hashFiles('esy.lock/**') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: build
        run: esy
      - name: build
        run: esy cp-bin
      - name: examples tests
        run: node examples/runTests.js

      - name: Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: ppx

      - name: rm the esy build stuff, don't need to cache that
        run: rm -rf ~/.esy/3_*/b/

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Check the issue
      - working-directory: .github/actions
        run: npm i
      - working-directory: .github/actions
        id: check
        run: node check.js --no-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download linux artifacts
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest
          path: binaries/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@master
        with:
          name: macOS-latest
          path: binaries/darwin

      - name: Download windows artifacts
        uses: actions/download-artifact@master
        with:
          name: windows-latest
          path: binaries/windows

      - name: Move artifacts
        run: |
          mkdir -p dist
          mv binaries/darwin/ppx dist/get_in_ppx-darwin-x64.exe
          mv binaries/windows/ppx dist/get_in_ppx-win-x64.exe
          mv binaries/linux/ppx dist/get_in_ppx-linux-x64.exe
          rm -rf binaries

      - name: Bump the npm version
        run: |
          npm version ${{ steps.check.outputs.version }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am 'version ${{ steps.check.outputs.version }}'

      # Test out the package
      - name: pack it up & test it out
        run: |
          npm pack
          cd dist_examples/bsb-7
          npm i
          npm i ../../get_in_ppx-${{ steps.check.outputs.version }}.tgz
          npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push the version bump up
        run: git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}