name: test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: setup
        run: npm i -g esy@latest

      - uses: actions/cache@v1
        with:
          path: ~/.esy
          key: ${{ runner.os }}-node-${{ hashFiles('esy.lock/**') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: build
        run: esy
      - name: examples tests
        run: node examples/runTests.js
      - name: rm the esy build stuff, don't need to cache that
        run: rm -rf ~/.esy/3_*/b/