name: test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # esy
      - name: setup
        run: |
          npm install -g esy@latest cross-env
      - name: build
        run: esy
      - name: examples tests
          run: node examples/runTests.js